### ISSUE TITLE
Regarding GBSG parameters

### ISSUE THREAD

**Issue by arturomoncadatorres** [czifan/DeepSurv.pytorch#4]
I was going through the code to replicate the experiments in the original paper. Specifically, I was looking into the GBSG one. In Table 3, the parameters for said experiment show that L2 regularization has a value of 6.551:

![image](https://user-images.githubusercontent.com/37126116/87572066-4a928b00-c6cb-11ea-817b-92416a5af341.png)

However, in the [`gbsg.ini`](https://github.com/czifan/DeepSurv.pytorch/blob/master/configs/gbsg.ini), `l2_reg` is set to 0. Is this just a typo/oversight or am I missing something?

**Comment by czifan** [comment]
Thank you for pointing it out. This code is not the official version, which is reproduced after I read the paper. I have adjusted some parameters by myself. Because it is easy to modify the configuration parameter file, I suggest you do experiments strictly according to the parameters of the paper.

**Comment by czifan** [comment]
> I was going through the code to replicate the experiments in the original paper. Specifically, I was looking into the GBSG one. In Table 3, the parameters for said experiment show that L2 regularization has a value of 6.551:
> 
> ![image](https://user-images.githubusercontent.com/37126116/87572066-4a928b00-c6cb-11ea-817b-92416a5af341.png)
> 
> However, in the [`gbsg.ini`](https://github.com/czifan/DeepSurv.pytorch/blob/master/configs/gbsg.ini), `l2_reg` is set to 0. Is this just a typo/oversight or am I missing something?

Thank you for pointing it out. This code is not the official version, which is reproduced after I read the paper. I have adjusted some parameters by myself. Because it is easy to modify the configuration parameter file, I suggest you do experiments strictly according to the parameters of the paper.

**Comment by arturomoncadatorres** [comment]
Of course, I understand. Thanks! I just wanted to be sure
